///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//	Project:           Project 2 - Text Analysis GUI
//	File Name:         AssemblyInfo.cs
//	Description:       Contains program information, generated by Visual Studio and edited 
//							relevant information
//	Course:            CSCI 2210 - Data Structures	
//	Author:            Brett Hamilton, hamiltonb@etsu.edu, Dept. of Computing, East Tennessee State University
//	Created:           Monday, September 30, 2019
//	Copyright:         Brett Hamilton, 2019
//
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle ("Text Analysis")]
[assembly: AssemblyDescription ("Text Analysis Project, Windows Version - The greatest " +
	"text analysis toolkit that ever existed. All other text analyzers are now obsolete. " +
	"If there was an Olympic games event for text analysis, this toolkit would bring home " +
	"gold.")]
[assembly: AssemblyConfiguration ("")]
[assembly: AssemblyCompany ("CSCI 2210 Brett Hamilton, Inc.")]
[assembly: AssemblyProduct ("Text Analysis Toolkit")]
[assembly: AssemblyCopyright ("Copyright © Brett Hamilton, 2019")]
[assembly: AssemblyTrademark ("")]
[assembly: AssemblyCulture ("")]

// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.  If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible (false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid ("8cdb735e-7f76-42d8-bf76-07034451d238")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion ("1.0.0.1")]
[assembly: AssemblyFileVersion ("1.0.0.1")]
