///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//	Project:           Project 2 - Text Analysis GUI
//	File Name:         SplashScreenForm.Designer.cs
//	Description:       Required code for the splash screen, generated by Visual Studio, provides necessary
//							code for form controls and display
//	Course:            CSCI 2210 - Data Structures	
//	Author:            Brett Hamilton, hamiltonb@etsu.edu, Dept. of Computing, East Tennessee State University
//	Created:           Monday, September 30, 2019
//	Copyright:         Brett Hamilton, 2019
//
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

namespace TextAnalysis
{
	partial class SplashScreenForm
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose (bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose ( );
			}
			base.Dispose (disposing);
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent ( )
		{
			this.components = new System.ComponentModel.Container();
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SplashScreenForm));
			this.splashVersionLabel = new System.Windows.Forms.Label();
			this.splashTimer = new System.Windows.Forms.Timer(this.components);
			this.titleLabel = new System.Windows.Forms.Label();
			this.pictureBoxLogo = new System.Windows.Forms.PictureBox();
			((System.ComponentModel.ISupportInitialize)(this.pictureBoxLogo)).BeginInit();
			this.SuspendLayout();
			// 
			// splashVersionLabel
			// 
			this.splashVersionLabel.AutoSize = true;
			this.splashVersionLabel.BackColor = System.Drawing.Color.White;
			this.splashVersionLabel.Font = new System.Drawing.Font("Calibri", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.splashVersionLabel.Location = new System.Drawing.Point(311, 353);
			this.splashVersionLabel.Name = "splashVersionLabel";
			this.splashVersionLabel.Size = new System.Drawing.Size(133, 24);
			this.splashVersionLabel.TabIndex = 3;
			this.splashVersionLabel.Text = "Version 1.0.0.0";
			// 
			// splashTimer
			// 
			this.splashTimer.Enabled = true;
			this.splashTimer.Interval = 3500;
			this.splashTimer.Tick += new System.EventHandler(this.SplashTimer_Tick);
			// 
			// titleLabel
			// 
			this.titleLabel.AutoSize = true;
			this.titleLabel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(199)))), ((int)(((byte)(44)))));
			this.titleLabel.Font = new System.Drawing.Font("Calibri", 30F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.titleLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(30)))), ((int)(((byte)(66)))));
			this.titleLabel.Location = new System.Drawing.Point(32, 284);
			this.titleLabel.Name = "titleLabel";
			this.titleLabel.Size = new System.Drawing.Size(421, 49);
			this.titleLabel.TabIndex = 4;
			this.titleLabel.Text = "TEXT ANALYSIS TOOLKIT";
			// 
			// pictureBoxLogo
			// 
			this.pictureBoxLogo.Image = global::Project2.Properties.Resources.shield_logo;
			this.pictureBoxLogo.Location = new System.Drawing.Point(12, 12);
			this.pictureBoxLogo.Name = "pictureBoxLogo";
			this.pictureBoxLogo.Size = new System.Drawing.Size(461, 256);
			this.pictureBoxLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.pictureBoxLogo.TabIndex = 0;
			this.pictureBoxLogo.TabStop = false;
			// 
			// SplashScreenForm
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.Color.White;
			this.ClientSize = new System.Drawing.Size(485, 395);
			this.Controls.Add(this.titleLabel);
			this.Controls.Add(this.splashVersionLabel);
			this.Controls.Add(this.pictureBoxLogo);
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
			this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
			this.Name = "SplashScreenForm";
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "SplashScreenForm";
			this.TransparencyKey = System.Drawing.Color.White;
			this.Load += new System.EventHandler(this.SplashScreenForm_Load);
			((System.ComponentModel.ISupportInitialize)(this.pictureBoxLogo)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.PictureBox pictureBoxLogo;
		private System.Windows.Forms.Label splashVersionLabel;
		private System.Windows.Forms.Timer splashTimer;
		private System.Windows.Forms.Label titleLabel;
	}
}