///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//	Project:           Project 2 - Text Analysis GUI
//	File Name:         AboutBoxForm.Designer.cs
//	Description:       Required code for the user info form, generated by Visual Studio, provides necessary
//							code for form controls and display
//	Course:            CSCI 2210 - Data Structures	
//	Author:            Brett Hamilton, hamiltonb@etsu.edu, Dept. of Computing, East Tennessee State University
//	Created:           Monday, September 30, 2019
//	Copyright:         Brett Hamilton, 2019
//
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

namespace TextAnalysis
{
	partial class UserInfo
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose (bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose ( );
			}
			base.Dispose (disposing);
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent ( )
		{
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UserInfo));
			this.fNameLabel = new System.Windows.Forms.Label();
			this.emailLabel = new System.Windows.Forms.Label();
			this.lNameLabel = new System.Windows.Forms.Label();
			this.phoneLabel = new System.Windows.Forms.Label();
			this.instructionsLabel = new System.Windows.Forms.Label();
			this.fNameTextBox = new System.Windows.Forms.TextBox();
			this.lNameTextBox = new System.Windows.Forms.TextBox();
			this.emailTextBox = new System.Windows.Forms.TextBox();
			this.phoneTextBox = new System.Windows.Forms.TextBox();
			this.okButton = new System.Windows.Forms.Button();
			this.cancelButton = new System.Windows.Forms.Button();
			this.SuspendLayout();
			// 
			// fNameLabel
			// 
			this.fNameLabel.AutoSize = true;
			this.fNameLabel.Location = new System.Drawing.Point(31, 67);
			this.fNameLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
			this.fNameLabel.Name = "fNameLabel";
			this.fNameLabel.Size = new System.Drawing.Size(75, 18);
			this.fNameLabel.TabIndex = 0;
			this.fNameLabel.Text = "First Name";
			// 
			// emailLabel
			// 
			this.emailLabel.AutoSize = true;
			this.emailLabel.Location = new System.Drawing.Point(31, 131);
			this.emailLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
			this.emailLabel.Name = "emailLabel";
			this.emailLabel.Size = new System.Drawing.Size(100, 18);
			this.emailLabel.TabIndex = 1;
			this.emailLabel.Text = "E-Mail Address";
			// 
			// lNameLabel
			// 
			this.lNameLabel.AutoSize = true;
			this.lNameLabel.Location = new System.Drawing.Point(31, 99);
			this.lNameLabel.Name = "lNameLabel";
			this.lNameLabel.Size = new System.Drawing.Size(72, 18);
			this.lNameLabel.TabIndex = 2;
			this.lNameLabel.Text = "Last Name";
			// 
			// phoneLabel
			// 
			this.phoneLabel.AutoSize = true;
			this.phoneLabel.Location = new System.Drawing.Point(31, 163);
			this.phoneLabel.Name = "phoneLabel";
			this.phoneLabel.Size = new System.Drawing.Size(102, 18);
			this.phoneLabel.TabIndex = 3;
			this.phoneLabel.Text = "Phone Number";
			// 
			// instructionsLabel
			// 
			this.instructionsLabel.AutoSize = true;
			this.instructionsLabel.ForeColor = System.Drawing.Color.Red;
			this.instructionsLabel.Location = new System.Drawing.Point(31, 18);
			this.instructionsLabel.Name = "instructionsLabel";
			this.instructionsLabel.Size = new System.Drawing.Size(377, 18);
			this.instructionsLabel.TabIndex = 4;
			this.instructionsLabel.Text = "Please fill in your name, e-mail address, and phone number.";
			// 
			// fNameTextBox
			// 
			this.fNameTextBox.Location = new System.Drawing.Point(170, 60);
			this.fNameTextBox.Name = "fNameTextBox";
			this.fNameTextBox.Size = new System.Drawing.Size(295, 25);
			this.fNameTextBox.TabIndex = 5;
			this.fNameTextBox.Click += new System.EventHandler(this.TextBox_Click);
			this.fNameTextBox.Enter += new System.EventHandler(this.FNameTextBox_Enter);
			// 
			// lNameTextBox
			// 
			this.lNameTextBox.Location = new System.Drawing.Point(170, 92);
			this.lNameTextBox.Name = "lNameTextBox";
			this.lNameTextBox.Size = new System.Drawing.Size(295, 25);
			this.lNameTextBox.TabIndex = 6;
			this.lNameTextBox.Click += new System.EventHandler(this.TextBox_Click);
			this.lNameTextBox.Enter += new System.EventHandler(this.LNameTextBox_Enter);
			// 
			// emailTextBox
			// 
			this.emailTextBox.Location = new System.Drawing.Point(170, 124);
			this.emailTextBox.Name = "emailTextBox";
			this.emailTextBox.Size = new System.Drawing.Size(295, 25);
			this.emailTextBox.TabIndex = 7;
			this.emailTextBox.Text = "example@url.com";
			this.emailTextBox.Click += new System.EventHandler(this.TextBox_Click);
			this.emailTextBox.Enter += new System.EventHandler(this.EmailTextBox_Enter);
			// 
			// phoneTextBox
			// 
			this.phoneTextBox.Location = new System.Drawing.Point(170, 156);
			this.phoneTextBox.Name = "phoneTextBox";
			this.phoneTextBox.Size = new System.Drawing.Size(295, 25);
			this.phoneTextBox.TabIndex = 8;
			this.phoneTextBox.Text = "(999) 999-9999";
			this.phoneTextBox.Click += new System.EventHandler(this.TextBox_Click);
			this.phoneTextBox.Enter += new System.EventHandler(this.PhoneTextBox_Enter);
			// 
			// okButton
			// 
			this.okButton.DialogResult = System.Windows.Forms.DialogResult.OK;
			this.okButton.Location = new System.Drawing.Point(127, 204);
			this.okButton.Name = "okButton";
			this.okButton.Size = new System.Drawing.Size(114, 30);
			this.okButton.TabIndex = 9;
			this.okButton.Text = "OK";
			this.okButton.UseVisualStyleBackColor = true;
			this.okButton.Click += new System.EventHandler(this.OkButton_Click);
			// 
			// cancelButton
			// 
			this.cancelButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
			this.cancelButton.Location = new System.Drawing.Point(278, 204);
			this.cancelButton.Name = "cancelButton";
			this.cancelButton.Size = new System.Drawing.Size(114, 30);
			this.cancelButton.TabIndex = 10;
			this.cancelButton.Text = "Cancel";
			this.cancelButton.UseVisualStyleBackColor = true;
			this.cancelButton.Click += new System.EventHandler(this.CancelButton_Click);
			// 
			// UserInfo
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 18F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(519, 246);
			this.Controls.Add(this.cancelButton);
			this.Controls.Add(this.okButton);
			this.Controls.Add(this.phoneTextBox);
			this.Controls.Add(this.emailTextBox);
			this.Controls.Add(this.lNameTextBox);
			this.Controls.Add(this.fNameTextBox);
			this.Controls.Add(this.instructionsLabel);
			this.Controls.Add(this.phoneLabel);
			this.Controls.Add(this.lNameLabel);
			this.Controls.Add(this.emailLabel);
			this.Controls.Add(this.fNameLabel);
			this.Font = new System.Drawing.Font("Calibri", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
			this.Margin = new System.Windows.Forms.Padding(4);
			this.Name = "UserInfo";
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Text Analysis User Information";
			this.ResumeLayout(false);
			this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.Label fNameLabel;
		private System.Windows.Forms.Label emailLabel;
		private System.Windows.Forms.Label lNameLabel;
		private System.Windows.Forms.Label phoneLabel;
		private System.Windows.Forms.Label instructionsLabel;
		private System.Windows.Forms.TextBox fNameTextBox;
		private System.Windows.Forms.TextBox lNameTextBox;
		private System.Windows.Forms.TextBox emailTextBox;
		private System.Windows.Forms.TextBox phoneTextBox;
		private System.Windows.Forms.Button okButton;
		private System.Windows.Forms.Button cancelButton;
	}
}